homeassistant:
  name: Heart of Gold
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: imperial
  time_zone: America/Denver
  customize: !include_dir_merge_named customization

http:
  api_password: !secret api_password

isy994: !include isy994/eddy.yaml

wink:
  access_token: !secret wink_token

group: !include_dir_merge_named group

zone: !include_dir_list zone

camera: !include_dir_list camera

alarm_control_panel:
  platform: manual
  name: alarm
  code: !secret alarm_code
  pending_time: 60
  trigger_time: 120

light:
  platform: lifx
  broadcast: 192.168.1.255

device_tracker: !include_dir_list device_tracker

media_player: !include media_players.yaml

panel_iframe: !include_dir_named panel_iframe

mqtt: !include mqtt/hass.yaml

thermostat: !include_dir_list thermostat

sensor: !include_dir_list sensor

logger: !include loggers.yaml

# switch: !include_dir_list switch

automation: !include_dir_list automation

notify: !include_dir_list notify

input_slider: !include input_sliders.yaml

input_boolean: !include input_booleans.yaml

proximity: !include_dir_list proximity

script: !include_dir_named scripts

alexa:
  intents: !include_dir_named alexa_intents

shell_command: !include shell_commands.yaml

## ENABLES
sun:

logbook:

history:

frontend:

conversation:
