- platform: plex

- platform: firetv
  host: localhost:5556
  name: Beeblebrox (FireTV)

- platform: firetv
  host: localhost:5557
  name: Agrajag (FireTV)

# - platform: samsungtv
#   host: 192.168.1.111
#   name: Living Room TV

# - platform: samsungtv
#   host: 192.168.1.117
#   name: Porch TV