alias: Close Garage Door
trigger:
  - platform: zone
    entity_id:
      - device_tracker.teagan_phone
      - device_tracker.grace_phone
    zone: zone.home
    event: 'leave'
  - platform: state
    entity_id:
      - device_tracker.teagan_phone
      - device_tracker.grace_phone
    from: 'home'
    to: 'not_home'
    for:
      minutes: 4
  - platform: state
    entity_id: group.family
    state: 'not_home'
    for:
      minutes: 10
  - platform: state
    entity_id: cover.garage_door
    state: 'open'
    for:
      hours: 2
condition:
  condition: state
  entity_id: input_boolean.garage_is_closing
  state: 'off'
action:
  - service: script.garage_door_action
    data:
      action: 'close'
