alias: Dining Room Light Turns Off
trigger:
  - platform: state
    entity_id: switch.dining_room_ceiling_light
    from: 'on'
    to: 'off'
action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.light_from_motion_dining
