alias: Enter Movie Mode
trigger:
   - platform: template
     value_template: >
       {{
         states.media_player.tv_un55ku6300.state == 'playing'
         and
         states.media_player.tv_un55ku6300.attributes.media_content_type == 'movie'
         and
         states.sun.sun.state == 'below_horizon'
       }}
action:
  - service: script.enter_movie_mode
