alias: Garage Opening Flag
trigger:
  - platform: template
    value_template: >
      {{ states.cover.garage_door.attributes.current_position | int < 10 }}
action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.garage_is_closing
