alias: Turn Kitchen Light Off
trigger:
  - platform: state
    entity_id: switch.kitchen_light
    from: 'on'
    to: 'off'
action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.light_from_motion_kitchen
