alias: Open Garage Door
trigger:
  - platform: zone
    entity_id:
      - device_tracker.teagan_phone
      - device_tracker.grace_phone
    zone: zone.home
    event: enter
  - platform: state
    entity_id:
      - device_tracker.teagan_phone
      - device_tracker.grace_phone
    from: 'not_home'
    to: 'home'
condition:
  condition: state
  entity_id: input_boolean.garage_is_opening
  state: 'off'
action:
  - service: script.garage_door_action
    data:
      action: 'open'
