alias: Turn On Kitchen Light
trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_motion
    from: 'off'
    to: 'on'
condition:
  - condition: state
    entity_id: switch.kitchen_light
    state: 'off'
action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.light_from_motion_kitchen
  - service: switch.turn_on
    data:
      entity_id: switch.kitchen_light
