alias: Turn Off Dining Room Light - Motion
trigger:
  - platform: state
    entity_id: binary_sensor.dining_room_motion
    from: 'on'
    to: 'off'
condition:
  - condition: state
    entity_id: input_boolean.light_from_motion_dining
    state: 'on'
action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.light_from_motion_dining
  - service: switch.turn_off
    data:
      entity_id: switch.dining_room_ceiling_light
