alias: Turn Off Kitchen Light - Motion
trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_motion
    from: 'on'
    to: 'off'
condition:
  - condition: state
    entity_id: input_boolean.light_from_motion_kitchen
    state: 'on'
action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.light_from_motion_kitchen
  - service: switch.turn_off
    data:
      entity_id: switch.kitchen_light
