alias: Teagan is Working From Home
trigger:
  - platform: state
    entity_id: calendar.teagan_work_from_home
    from: 'off'
    to: 'on'
action:
  - service: notify.slack__massroots
    data_template:
      message: >
        {%- set responses = [
          'It just tickles me pink to remind you that Teagan is working remote today',
          'Well isn\'t it just a breath of fresh air when Teagan works from home like today?!',
          'No one is more excited than I am that Teagan won\'t be showing her face at the office today!'] -%}
        Eddie> {{ responses | random }}
