alias: Close Garage Door
trigger:
# Close we leave the house
  - platform: zone
    entity_id:
      - device_tracker.grace_nexus_6
      - device_tracker.teagan_nexus_6
    zone: zone.home
    event: leave
# In case we leave it open over night
  - platform: state
    entity_id: switch.garage_door
    from: 'on'
    to: 'off'
    for:
      hours: 2
# Sometimes the zoning trigger doesn't fire
  - platform: state
    entity_id: group.family
    from: 'home'
    to: 'not_home'
    for:
      minutes: 5
condition:
  condition: state
  entity_id: switch.garage_door
  state: 'off'
action:
  service: switch.turn_on
  data:
    entity_id: switch.garage_door