alias: Dining Motion
trigger:
  platform: state
  entity_id: sensor.dining_room_motion
  from: 'off'
  to: 'on'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: switch.dining_room_ceiling_light
      state: 'off'
    - condition: or
      conditions:
        - condition: time
          after: '18:00:00'
        - condition: time
          before: '10:00:00'
action:
  - service: switch.turn_on
    data:
      entity_id: switch.dining_room_ceiling_light
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.dining_light_from_sensor