alias: No Motion In Dining Room
trigger:
  platform: state
  entity_id: sensor.dining_room_motion
  from: 'on'
  to: 'off'
condition:
  condition: state
  entity_id: input_boolean.dining_light_from_sensor
  state: 'on'
action:
  - service: switch.turn_off
    data:
      entity_id: switch.dining_room_ceiling_light
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.dining_light_from_sensor