alias: Front Door is Ajar - Occupied
trigger:
  platform: state
  entity_id: sensor.front_door_sensor
  from: 'off'
  to: 'on'
  for:
    minutes: 10
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: device_tracker.grace
      state: 'home'
    - condition: state
      entity_id: device_tracker.teagan
      state: 'home'
    - condition: state
      entity_id: device_tracker.persia
      state: 'home'
action:
  - service: notify.hog_sns
    data:
      message: 'Front door has been open for over 10 minutes.'
      target: !secret aws_topic_info
      title: 'Front Door Ajar'