alias: Thermostat - Cool Home
trigger:
  platform: template
  value_template: >
    {{
      (float(states.thermostat.breathosmart.attributes.current_temperature) > float(states.input_slider.hvac_home_cool_set.state)
      or (
        states.thermostat.breathosmart.attributes.system_mode == 'cool' and
        float(states.thermostat.breathosmart.state) != float(states.input_slider.hvac_home_cool_set.state)
      ))
      and (
        states.device_tracker.teagan.state == 'home'
        or states.device_tracker.grace.state == 'home'
        or states.device_tracker.persia.state == 'home'
      )
    }}
action:
  - service: thermostat.set_hvac_mode
    data:
      entity_id: thermostat.breathosmart
      hvac_mode: 'cool'
  - service: thermostat.set_temperature
    data_template:
      entity_id: thermostat.breathosmart
      temperature: '{{ float(states.input_slider.hvac_home_cool_set.state) }}'