alias: Thermostat - Heat Away
trigger:
  platform: template
  value_template: >
    {{
      (float(states.thermostat.breathosmart.attributes.current_temperature) < float(states.input_slider.hvac_away_heat_set.state)
      or (
        states.thermostat.breathosmart.attributes.system_mode == 'heat' and
        float(states.thermostat.breathosmart.state) != float(states.input_slider.hvac_away_heat_set.state)
      ))
      and states.device_tracker.teagan.state != 'home'
      and states.device_tracker.grace.state != 'home'
      and states.device_tracker.persia.state != 'home'
    }}
condition:
  condition: state
  entity_id: input_boolean.on_vaca
  state: 'off'
action:
  - service: thermostat.set_hvac_mode
    data:
      entity_id: thermostat.breathosmart
      hvac_mode: 'heat'
  - service: thermostat.set_temperature
    data_template:
      entity_id: "thermostat.breathosmart"
      temperature: '{{ float(states.input_slider.hvac_away_heat_set.state) }}'